blazephp.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp.c -o blazephp.lo 
kernel/main.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/kernel/exit.c -o kernel/exit.lo 
blazephp/struct.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/struct.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/struct.zep.c -o blazephp/struct.lo 
blazephp/helloworld.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/helloworld.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/helloworld.zep.c -o blazephp/helloworld.lo 
blazephp/lock.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/lock.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/lock.zep.c -o blazephp/lock.lo 
blazephp/log.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/log.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/log.zep.c -o blazephp/log.lo 
blazephp/request.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/request.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/request.zep.c -o blazephp/request.lo 
blazephp/session.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/session.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/session.zep.c -o blazephp/session.lo 
blazephp/sessionconfig.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/sessionconfig.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/sessionconfig.zep.c -o blazephp/sessionconfig.lo 
blazephp/uniqueid.lo: /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/uniqueid.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/media/sf_devhttpd/BlazePHP/phpext/blazephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /media/sf_devhttpd/BlazePHP/phpext/blazephp/ext/blazephp/uniqueid.zep.c -o blazephp/uniqueid.lo 
$(phplibdir)/blazephp.la: ./blazephp.la
	$(LIBTOOL) --mode=install cp ./blazephp.la $(phplibdir)

./blazephp.la: $(shared_objects_blazephp) $(BLAZEPHP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_blazephp) $(BLAZEPHP_SHARED_LIBADD)

